### ISSUE TITLE
Kinvey.plist Missing

### ISSUE THREAD

**Issue by Harry00742** [davidtucker/WaterCooler-Demo#1]
I have downloaded the whole source code . But there is No Kinvey.plist file in that. So tried by Manually adding plist with same name. But that is giving me error and Not able to Run the code. Kindly Help me out for the same.

**Comment by davidtucker** [comment]
If you update the app and secret key with your Kinvey values in the app delegate, you won't need to have the Kinvey.plist.  Read the section "Getting Started with Kinvey" here: http://www.smashingmagazine.com/2015/03/30/mobile-backend-service-practice-part1/

**Comment by Isuru-Nanayakkara** [comment]
Even after adding the app and secret keys to the AppDelegate file, I still got this error. I had to remove the Kinvey.plist entry from the Copy Bundle Resources list to get rid of it.
